### ISSUE TITLE
App Uninstall should work only with IDs

### ISSUE THREAD

**Issue by zaiste** [saleor/saleor-cli#446]
`app uninstall` should accept Saleor App ID and not its name as input parameter.

**Comment by krzysztofwolski** [comment]
@zaiste 
Was able to uninstall, but…
- [ ] command help does not provide info that I can specify ID - needs to be added
- [ ] help message still asks for an app name
- [ ] arg name app kind of confusing me - at first was not sure if that's an app name or add id. Maybe appID or just ID would be a better choice?
- [ ] if I just run `saleor app uninstall` without arguments I get GQL error. Users should be presented with a list of the apps to choose or get information about missing ID

```
Uninstalling undefined the Saleor App from your Dashboard...errors:
  errors:
    - message: Argument "id" of required type ID!" provided the variable "$app" which
        was not provided
      extensions:
        exception:
          code: GraphQLError
  extensions:
    cost:
      requestedQueryCost: 0
      maximumAvailable: 50000
```

**Comment by krzysztofwolski** [comment]
- [ ] App uninstall without the ID passed as argument: Help message is displayed, but there's no information on which argument is required. Not sure if that classifies as bug, maybe an improvement? 
- [ ] If I try to uninstall an already uninstalled app, I get GQL error instead of a clear message whats the issue. Should be handled in a nicer way.


![Image](https://user-images.githubusercontent.com/5188636/195874505-6f984fd7-b00f-411f-a824-5c1a998b456f.png)

**Comment by zaiste** [comment]
Continued in #475
